张量 Tensor 是mindspore 网络运算中的基本数据结构
导入需要的模块和接口

In [1]:
import numpy as np
from mindspore import Tensor,context
from mindspore import dtype as mstype
context.set_context(mode = context.GRAPH_MODE,device_target = "CPU")#设置为图模式，指定CPU进行运算

## 初始化张量
初始化方式很多： 构造张量的时候 支持传入Tensor、float、int、bool、tuple、list和Numpy.array类型
 - 根据数据直接生成
可以根据数据直接创建张量，数据类型可以设置或者自动推断

In [3]:
x = Tensor(0.1)
print("datatype of x : {}".format(type(x)))
print("value of x : {}".format(x))

datatype of x ::<class 'mindspore.common.tensor.Tensor'>
value of x ::0.1


In [4]:
arr = np.array([1,0,1,0])
x_np = Tensor(arr)
print("datatype of x : {}".format(type(x_np)))
print("value of x : {}".format(x_np))

datatype of x <class 'mindspore.common.tensor.Tensor'>
value of x [1 0 1 0]


### 继承另一个张量的属性，形成新的张量  （大小的属性一致）

In [6]:
from mindspore import ops
oneslike = ops.OnesLike()
x = Tensor(np.array([[1,2],[3,4]]).astype(np.int32))
print(x)
output = oneslike(x) # 获取大小一致的一个张量
print("datatype of output : {}".format(type(output)))
print(output) 

[[1 2]
 [3 4]]
datatype of output : <class 'mindspore.common.tensor.Tensor'>
[[1 1]
 [1 1]]


### 指定大小 （shape）元组进行大小恒定的张量

In [7]:

from mindspore.ops import operations as opts
shape = (2,2)
ones = opts.Ones()
output = ones(shape,mstype.float32)
print(output)

zeros = ops.Zeros()
output = zeros(shape,mstype.float32)
print(output)


[[1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]]


## 张量的属性
- shape 形状 是一个tuple
- dtype 是mindspore的数据类型

In [10]:
x = Tensor([[4],[5]])
print("datatype of x : {}".format(x.dtype))
print("shape of x : {}".format(x.shape))

datatype of x : Int32
shape of x : (2, 1)


## 张量运算
基本的算术运算、线性代数运算，矩阵处理（转置、标引，切片），采样

In [18]:
#索引切片
t = Tensor(np.array([[1,2,3],[4,5,6]]))
print(t[:2])
print(t[0])
print(t[...,-1])
print(t[...,-2])
print(t[:,0])
print(t[:,1])
print(t[...,1])

[[1 2 3]
 [4 5 6]]
[1 2 3]
[3 6]
[2 5]
[1 4]
[2 5]
[2 5]


In [19]:
# 使用Concat 连接 ，相当于 vstack（二维时） 在给定方向上连接 总维度不变
 
d1 = Tensor(np.array([[0,1],[2,3]]))
d2 = Tensor(np.array([[4,5],[6,7]]))
op = ops.Concat()
output = op((d1,d2))
print(output)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [20]:
# 使用 Stack 从另一个维度上讲两个两张合并起来 总维度+1
d1 = Tensor(np.array([[0,1],[2,3]]))
d2 = Tensor(np.array([[4,5],[6,7]]))
op = ops.Stack()
output = op((d1,d2))
print(output)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [22]:
# 乘法 Mul
d1 = Tensor(np.array([[0,1],[2,3]]))
d2 = Tensor(np.array([[4,5],[6,7]]))
op = ops.Mul()
output = op(d1,d2)
print(output)

[[ 0  5]
 [12 21]]


### 与Numpy互相转换

In [25]:
zeros = ops.Zeros()
output = zeros((2,2),mstype.int32)
print(type(output))
n_output = output.asnumpy()
print(type(n_output))

<class 'mindspore.common.tensor.Tensor'>
<class 'numpy.ndarray'>
